// Сборка dist/index.html (file://): вкладка «3D» строится, GLB скачивается.
import { chromium } from 'playwright-core';
import { pathToFileURL, fileURLToPath } from 'node:url';
import { resolve } from 'node:path';
import { readFileSync } from 'node:fs';
const out = fileURLToPath(new URL('./qa/', import.meta.url));
const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, acceptDownloads: true });
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push('PAGEERROR ' + e.message));
page.on('console', (m) => m.type() === 'error' && errors.push(m.text().slice(0, 300)));
await page.goto(pathToFileURL(resolve('dist/index.html')).href);
await page.waitForSelector('.topbar');
const t0 = Date.now();
await page.getByRole('button', { name: '3D', exact: true }).click();
await page.getByRole('button', { name: 'Сгенерировать', exact: true }).first().click();
await page.waitForFunction(() => /draw calls/.test(document.querySelector('.v3-perf')?.textContent ?? ''), null, { timeout: 30000 });
const openMs = Date.now() - t0;
await page.waitForTimeout(1500);
await page.screenshot({ path: out + 'dist-3d.png' });
const [dl] = await Promise.all([page.waitForEvent('download', { timeout: 60000 }), page.getByRole('button', { name: /Скачать \.glb/ }).click()]);
const p = out + 'dist-blockout.glb';
await dl.saveAs(p);
const buf = readFileSync(p);
const jlen = buf.readUInt32LE(12);
const json = JSON.parse(buf.subarray(20, 20 + jlen).toString('utf8'));
console.log(JSON.stringify({ openMs, glb: { bytes: buf.length, magic: buf.subarray(0, 4).toString(), version: buf.readUInt32LE(4), meshes: json.meshes.length, nodes: json.nodes.length, images: json.images?.length ?? 0, accessors: json.accessors.length }, side: (await page.locator('.v3-times').innerText()), errors }, null, 1));
await browser.close();
